### ISSUE TITLE
Json list doesn't contain public suffixes with the wildcard

### ISSUE THREAD

**Issue by adbuker** [fbraz3/publicsuffix-json#2]
The issue is in the fact, that provided json doesn't contain public suffixes with the wildcard whereas the origin [list](https://publicsuffix.org/list/public_suffix_list.dat) does. As for example 
```code
// ck : https://en.wikipedia.org/wiki/.ck
*.ck
!www.ck
```
but json contains only `!www.ck`

**Comment by fbraz3** [comment]
Hi,

updated source code to import wildcards as is from origin list.

thanks for contributing =)
